apiVersion: v1
kind: Service
metadata:
  labels:
    {{ include "helm-charts.labels" . | nindent 4 }}
  name: {{ .Values.service.name | quote }}
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
  selector:
    {{ include "helm-charts.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
      matchLabels:
        app: "react-ui"
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
        - name: "react-ui"
          image: "deekshithsn/ui"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080